CREATE TABLE IF NOT EXISTS recycle_location(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(150) NOT NULL COMMENT '施設名',
    address VARCHAR(255) NOT NULL COMMENT '住所',
    latitude DECIMAL(10, 7) NOT NULL COMMENT '緯度',
    longitude DECIMAL(10, 7) NOT NULL COMMENT '経度',
    business_hours TEXT COMMENT '営業時間',
    PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;